<?php

namespace MB\MyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BiuroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiuroRepository extends EntityRepository
{
}
