<?php

namespace MB\MyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfficePresentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficePresentRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'ASC'));
    }
}
